language: php
php:
  - 7
  - 5.6
  - 5.5


install:
  - composer install


script:
  - phpunit --coverage-text


before_script:
  - echo 'date.timezone = "Asia/Shanghai"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
